### ISSUE TITLE
Package install broken?

### ISSUE THREAD

**Issue by nilshg** [nudomarinero/wquantiles#1]
Not sure about this, as I haven't used Python in a while and hence might be doing something wrong, but currently doing `pip install wquantiles` just adds a a folder named `wquantiles-0.3.dist-info` to my package folder, which doesn't contain the actual `.py` files that define the functions.

**Comment by nudomarinero** [comment]
There should also be a file called weighted.py in the package folder. Could you check if you have this file please?
The main methods can be imported using `from weighted import quantile, median`. I think I should clarify that.

**Comment by nilshg** [comment]
Sure, that was my point, the actual file containing the definitions was not installed. I downloaded it manually and it works fine, but the pip install didn't work.

**Comment by nudomarinero** [comment]
I have tried to reproduce the error with no success. 
Summarizing, when you run `pip install wquantiles` the folder `wquantiles-0.3.dist-info`  is added to `site-packages` but the file `weighted.py` is not. Hence, if you try to run `from weighted import quantile, median` it does not work unless you manually add `weighted.py` to `site-packages`. 
Could you please send me some information about your system (Operating System, Python version `python --version`, pip version `pip --version`, etc) so I can try to reproduce the error?

**Comment by nilshg** [comment]
It's Python 2.7.8, Anconda 2.3.0 (64-bit), with pip 7.1.2 on Windows 7 SP1.
If you can't reproduce it and no one else sees it, it might be a quirk on my machine.

**Comment by nudomarinero** [comment]
I have tried to reproduce the error in exactly the same system (Python 2.7.8, Anconda 2.3.0 (64-bit), with pip 7.1.2 on Windows 7 SP1) from a fresh install and could not find the problem. 
The file `weighted.py` is placed in `Anaconda\Lib\site-packages` when I execute `pip install wquantiles`.
![weighted](https://cloud.githubusercontent.com/assets/215599/10195657/a4381340-6786-11e5-9458-04e5b9a3b71e.PNG)

Perhaps it is a quirk on your system as you mention. If you need to debug this at some point down the line maybe you could try to create a conda isolated environment to make some tests. Anyway, at least the manual copy of the file works for you. Thank you for the report!
