### ISSUE TITLE
Please Document the Correct Module Name or Add a package-level `__init__`

### ISSUE THREAD

**Issue by madphysicist** [nudomarinero/wquantiles#3]
For your consideration:

This may be obvious in hindsight, but to use `wquantiles`, you have to `import weighted`. Not `import wquantiles` or `from wquantiles import ...`. This is a bit counter-intuitive and not explicitly documented. Took me a while to figure out why `python setup.py install` was successful but `python -c 'import wquantiles'` was not.

I do not have any particular problem with doing the import the way it is now, but I think it should be mentioned somewhere in README.md.

**Comment by madphysicist** [comment]
I just realized that an even simpler solution would be to rename `weighted.py` to `wquantiles.py`.

**Comment by nudomarinero** [comment]
Hello, 
Thank you for the comments. Yes, I should clarify that in the documentation. In a future release I will use something more meaningful like you propose. 
At the moment I think I should not just rename the module because it could break existing code.

**Comment by mattayes** [comment]
@nudomarinero: I mean, `wquantiles` is still in beta. Isn't that what betas are for? Breaking code while you're figuring out the public API?

**Comment by nudomarinero** [comment]
Sorry for the delay. I have already changed the name to ```wquantiles```.
